-- gp
CREATE TABLE "bm_acct_loan" (
  "txa_number" varchar COLLATE "pg_catalog"."default" NOT NULL,
  "txa_type" varchar COLLATE "pg_catalog"."default",
  "txa_status" varchar COLLATE "pg_catalog"."default",
  "txa_business_module" varchar COLLATE "pg_catalog"."default",
  "txn_organization_id" varchar COLLATE "pg_catalog"."default",
  "txn_type" varchar COLLATE "pg_catalog"."default",
  "txn_code" varchar COLLATE "pg_catalog"."default",
  "txn_system_date" timestamp(6),
  "txn_effective_date" timestamp(6),
  "txn_effective_amnt" numeric,
  "txn_effective_currency" varchar COLLATE "pg_catalog"."default",
  "txn_posting_date" date,
  "txn_posting_time" timestamp(6),
  "txn_posting_amnt" numeric,
  "txn_posting_currency" varchar COLLATE "pg_catalog"."default",
  "txn_settle_amnt" numeric,
  "txn_settle_currency" varchar COLLATE "pg_catalog"."default",
  "txn_markup_percent" numeric,
  "txn_exchange_rate" numeric,
  "txn_plastic_number" varchar COLLATE "pg_catalog"."default",
  "txn_card_number_post" varchar COLLATE "pg_catalog"."default",
  "txn_lbs_info" varchar COLLATE "pg_catalog"."default",
  "txn_country" varchar COLLATE "pg_catalog"."default",
  "txn_region" varchar COLLATE "pg_catalog"."default",
  "txn_channel" varchar COLLATE "pg_catalog"."default",
  "txn_sub_channel_1" varchar COLLATE "pg_catalog"."default",
  "txn_sub_channel_2" varchar COLLATE "pg_catalog"."default",
  "txn_mechant_number" varchar COLLATE "pg_catalog"."default",
  "txn_material_flag" varchar COLLATE "pg_catalog"."default",
  "txn_pos_ind" varchar COLLATE "pg_catalog"."default",
  "txn_auth_code" varchar COLLATE "pg_catalog"."default",
  "txn_batch_number" varchar COLLATE "pg_catalog"."default",
  "txn_voucher_number" varchar COLLATE "pg_catalog"."default",
  "txn_reference_number" varchar COLLATE "pg_catalog"."default",
  "txn_cust_number" varchar COLLATE "pg_catalog"."default",
  "txn_cust_name" varchar COLLATE "pg_catalog"."default",
  "txn_cust_group_id" varchar COLLATE "pg_catalog"."default",
  "txn_intr_start_date" date,
  "txn_statment_day_date" date,
  "txn_waive_intr_flag" varchar COLLATE "pg_catalog"."default",
  "txn_waive_latechg_flag" varchar COLLATE "pg_catalog"."default",
  "txn_chargeoff_flag" varchar COLLATE "pg_catalog"."default",
  "txn_chargeoff_amnt" numeric,
  "txn_chargeoff_date" date,
  "txn_chargeoff_rsn_cd" varchar COLLATE "pg_catalog"."default",
  "txn_orig_txa_number" varchar COLLATE "pg_catalog"."default",
  "txn_create_date" timestamp(6),
  "txn_last_update_date" timestamp(6),
  "txn_last_update_operator" varchar COLLATE "pg_catalog"."default",
  "txn_parent_txa_number" varchar COLLATE "pg_catalog"."default",
  "txn_stmt_repayment_tableid" varchar COLLATE "pg_catalog"."default",
  "pro_cd" varchar COLLATE "pg_catalog"."default",
  "txn_orig_txa_type" varchar COLLATE "pg_catalog"."default",
  "txn_parent_txa_type" varchar COLLATE "pg_catalog"."default",
  "txn_session_number" varchar COLLATE "pg_catalog"."default",
  "txn_connect_txa_number" varchar COLLATE "pg_catalog"."default",
  "txn_connect_txa_type" varchar COLLATE "pg_catalog"."default",
  "loan_plan_table_id" varchar COLLATE "pg_catalog"."default",
  "bal_trans_flag" varchar COLLATE "pg_catalog"."default",
  "compensatory_flag" varchar COLLATE "pg_catalog"."default",
  "joint_loan_flag" varchar COLLATE "pg_catalog"."default",
  "fus_id" varchar COLLATE "pg_catalog"."default",
  "loan_prin_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_intr_table_id" varchar COLLATE "pg_catalog"."default",
  "loan_fee_table_id" varchar COLLATE "pg_catalog"."default",
  "loan_payoff_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_pen_intr_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_cs_pen_intr_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_cs_intr_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_cs_loan_fee_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_cs_loan_prepay_table_id" varchar COLLATE "pg_catalog"."default",
  "txn_cs_loan_payoff_table_id" varchar COLLATE "pg_catalog"."default",
  "loan_billing_cycle" varchar COLLATE "pg_catalog"."default",
  "loan_payment_due_date" date,
  "first_payment_due_date" date,
  "last_payment_due_date" date,
  "loan_tenor" int4,
  "loan_fee_wavie_from" int4,
  "loan_fee_wavie_to" int4,
  "loan_status" varchar COLLATE "pg_catalog"."default",
  "loan_tenor_typ" varchar COLLATE "pg_catalog"."default",
  "loan_acq_ref_nbr" varchar COLLATE "pg_catalog"."default",
  "loan_operator_id" varchar COLLATE "pg_catalog"."default",
  "loan_mechant_name" varchar COLLATE "pg_catalog"."default",
  "loan_b018_merchant_typ" varchar COLLATE "pg_catalog"."default",
  "loan_order_number" varchar COLLATE "pg_catalog"."default",
  "loan_status_reason" varchar COLLATE "pg_catalog"."default",
  "loan_cast_tenor" int4,
  "loan_payment_tenor" int4,
  "loan_close_payment_date" date,
  "loan_curr_balance" numeric,
  "loan_contract_id" varchar COLLATE "pg_catalog"."default",
  "loan_channel_id" varchar COLLATE "pg_catalog"."default",
  "loan_total_balance" numeric,
  "loan_total_principal_balance" numeric,
  "loan_total_interest_balance" numeric,
  "loan_total_service_fee_balance" numeric,
  "discount_be_interest" numeric,
  "discount_interest" numeric,
  "loan_total_penalty_fee" numeric,
  "loan_total_penalty_exempt_amnt" numeric,
  "coupon_flow_id" varchar COLLATE "pg_catalog"."default",
  "loan_payment_date_dd" int4,
  "loan_daily_rate" numeric,
  "fus_daily_rate" numeric,
  "converted_daily_rate" numeric,
  "daily_rate_before" numeric,
  "loan_prepay_table_id" varchar COLLATE "pg_catalog"."default",
  "loan_contract_number" varchar COLLATE "pg_catalog"."default",
  "business_type" varchar COLLATE "pg_catalog"."default",
  "staff_name_lj" varchar COLLATE "pg_catalog"."default",
  "staff_id_type" varchar COLLATE "pg_catalog"."default",
  "staff_id_number" varchar COLLATE "pg_catalog"."default",
  "staff_account" varchar COLLATE "pg_catalog"."default",
  "check_digit" varchar COLLATE "pg_catalog"."default",
  "serial_num" varchar COLLATE "pg_catalog"."default",
  "loan_use" varchar COLLATE "pg_catalog"."default",
  "staff_cust_number" varchar COLLATE "pg_catalog"."default",
  "product_code" varchar COLLATE "pg_catalog"."default",
  "txn_late_charge_fee_table_id" varchar COLLATE "pg_catalog"."default",
  "compensatory_days" int4,
  "txn_lending_time" timestamp(6),
  "total_over_due_tenor" int4,
  "total_cmps_tenor" int4,
  "invest" varchar COLLATE "pg_catalog"."default",
  "reveal_mobel" varchar COLLATE "pg_catalog"."default",
  "back_fee_rate" numeric,
  "last_update_business_date" date,
  "hp_posting_amnt" numeric,
  "ot_posting_amnt" numeric,
  "fus_percentage" numeric,
  "hp_curr_balance" numeric,
  "ot_curr_balance" numeric,
  "continue_over_due_tenor" int4,
  "mark" varchar COLLATE "pg_catalog"."default",
  "txn_partner_pen_intr_table_id" varchar COLLATE "pg_catalog"."default",
  "last_update_time" timestamp(6),
  "create_time" timestamp(6),
  "loan_start_date" date,
  "real_channel" varchar COLLATE "pg_catalog"."default",
  "is_stock_order" varchar COLLATE "pg_catalog"."default",
  "asset_status" varchar COLLATE "pg_catalog"."default",
  "portfolio_code" varchar COLLATE "pg_catalog"."default",
  "has_loop" varchar COLLATE "pg_catalog"."default",
  "bank_inner_account" varchar COLLATE "pg_catalog"."default",
  "product_xindai_code" varchar COLLATE "pg_catalog"."default",
  "invest_code" varchar COLLATE "pg_catalog"."default",
  "daily_total_prin_bal" numeric,
  "hp_daily_total_prin_bal" numeric,
  PRIMARY KEY ("txa_number")
)
;
